# Configuration for Gitlab-CI.
# Builds appear on https://gitlab.com/buildroot.org/buildroot/pipelines

image: $CI_REGISTRY/buildroot.org/buildroot/base:20211120.1925

stages:
  - generate-gitlab-ci
  - build

generate-gitlab-ci-yml:
  stage: generate-gitlab-ci
  script: ./support/scripts/generate-gitlab-ci-yml support/misc/gitlab-ci.yml.in > generated-gitlab-ci.yml
  artifacts:
    paths:
      - generated-gitlab-ci.yml

buildroot-pipeline:
  stage: build
  trigger:
    include:
      - artifact: generated-gitlab-ci.yml
        job: generate-gitlab-ci-yml
    strategy: depend
