name: Sync with Upstream

env:
  # Required, URL to upstream (fork base)
  UPSTREAM_URL: "https://github.com/buildroot/buildroot.git"
  # Optional, defaults to main
  UPSTREAM_BRANCH: "master"
  # Optional, defaults to UPSTREAM_BRANCH
  DOWNSTREAM_BRANCH: "master"
  # Optional merge arguments
  MERGE_ARGS: ""
  # Optional push arguments
  PUSH_ARGS: ""

# This runs every sunday on 0000 UTC
on:
  schedule:
    - cron: '0 0 * * 0'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: dabreadman/sync-upstream-repo@v1.0.0.b
        with: 
          upstream_repo: ${{ env.UPSTREAM_URL }}
          upstream_branch: ${{ env.UPSTREAM_BRANCH }}
          downstream_branch: ${{ env.DOWNSTREAM_BRANCH }}
          token: ${{ secrets.GITHUB_TOKEN }}
          merge_args: ${{ env.MERGE_ARGS }}
          push_args: ${{ env.PUSH_ARGS }}

      - name: checkout repo
        uses: actions/checkout@main

      - name: init commit env
        run: |
          git config --global user.name "commit bot"
          git config --global user.email 953308023@qq.com

      - name: Check and update the kernel version
        run: |
          cd ${{ github.workspace }} 
          ls -lh
          cd ${{ github.workspace }}/configs/
          LOCAL_VERSION=`grep BR2_LINUX_KERNEL_CUSTOM_TARBALL_LOCATION reTerminal_64_defconfig`
          REMOTE_VERSION=`grep BR2_LINUX_KERNEL_CUSTOM_TARBALL_LOCATION raspberrypi4_64_defconfig`
          if [ "$LOCAL_VERSION" != "$REMOTE_VERSION"];then
            sed -i '/BR2_LINUX_KERNEL_CUSTOM_TARBALL_LOCATION/d' reTerminal_64_defconfig
            echo "$REMOTE_VERSION" >> reTerminal_64_defconfig
            git add reTerminal_64_defconfig
            git commit -m "sync kernel version with upstream" -a
          fi

      - name: 
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
